export const ActionConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_ERROR: 'REGISTER_ERROR',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',

  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',

  PROFILE_REQUEST: 'PROFILE_REQUEST',
  PROFILE_ERROR: 'PROFILE_ERROR',
  PROFILE_SUCCESS: 'PROFILE_SUCCESS',
  PROFILE_FLUSH: 'PROFILE_FLUSH',

  GENERATE_OTP_REQUEST: 'GENERATE_OTP_REQUEST',
  GENERATE_OTP_ERROR: 'GENERATE_OTP_ERROR',
  GENERATE_OTP_SUCCESS: 'GENERATE_OTP_SUCCESS',

  //Agents List

  MISSION_LIST_REQUEST: 'MISSION_LIST_REQUEST',
  MISSION_LIST_SUCCESS: 'MISSION_LIST_SUCCESS',
  MISSION_LIST_ERROR: 'MISSION_LIST_ERROR',

  MISSION_REPORT_SUBMIT_REQUEST: 'MISSION_REPORT_SUBMIT_REQUEST',
  MISSION_REPORT_SUBMIT_SUCCESS: 'MISSION_REPORT_SUBMIT_SUCCESS',
  MISSION_REPORT_SUBMIT_ERROR: 'MISSION_REPORT_SUBMIT_ERROR',
  MISSION_REPORT_SUBMIT_FLUSH: 'MISSION_REPORT_SUBMIT_FLUSH',

  MISSION_AGENTS_REQUEST: 'MISSION_AGENTS_REQUEST',
  MISSION_AGENTS_SUCCESS: 'MISSION_AGENTS_SUCCESS',
  MISSION_AGENTS_ERROR: 'MISSION_AGENTS_ERROR',
  MISSION_AGENTS_FLUSH: 'MISSION_AGENTS_FLUSH',

  BOOK_AGENTS_REQUEST: 'BOOK_AGENTS_REQUEST',
  BOOK_AGENTS_SUCCESS: 'BOOK_AGENTS_SUCCESS',
  BOOK_AGENTS_ERROR: 'BOOK_AGENTS_ERROR',

  // location
  LOCATION_SUCCESS: 'LOCATION_SUCCESS',
  LOCATION_ERROR: 'LOCATION_ERROR',

  //Payment
  MAKE_PAYMENT_REQUEST: 'MAKE_PAYMENT_REQUEST',
  MAKE_PAYMENT_SUCCESS: 'MAKE_PAYMENT_SUCCESS',
  MAKE_PAYMENT_ERROR: 'MAKE_PAYMENT_ERROR',
  MAKE_PAYMENT_FLUSH: 'MAKE_PAYMENT_FLUSH',

  GET_MISSION_REQUEST: 'GET_MISSION_REQUEST',
  GET_MISSION_SUCCESS: 'GET_MISSION_SUCCESS',
  GET_MISSION_ERROR: 'GET_MISSION_ERROR',
  GET_MISSION_FLUSH: 'GET_MISSION_FLUSH',

  SOCKET_CONNECTION: 'SOCKET_CONNECTION',
  SOCKET_DISCONNECT: 'SOCKET_DISCONNECT',
  SOCKET_FLUSH: 'SOCKET_FLUSH',
};
